version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nids-container
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./filekey.key:/app/filekey.key
    networks:
      - honeypot_network
    restart: unless-stopped
    command: ./start.sh

  cowrie:
    image: cowrie/cowrie
    ports:
      - "2222:2222"
    volumes:
      - ./ssh_bruteforce/cowrie/etc:/cowrie/cowrie-git/etc
    networks:
      - honeypot_network

networks:
  honeypot_network:
    driver: bridge
