version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ndis-container
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
      - ./filekey.key:/app/filekey.key
    restart: unless-stopped
    command: ./start.sh
