version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ndis-container
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    command: sudo python3 nids.py --source_email $src_email --password $password --dest_email $dst_email -i $interval
